wheel_width: 0.04 # The width of the wheels
wheel_radius: 0.1 # The radius of the wheels
wheel_base: 0.26 # The distance between the centers wheels
chassis_length: 0.5 # The length of the main chassis link
chassis_thinkness: 0.07 # The thickness of the plate that forms the chassis
