<?xml version="1.0" ?>

<robot name="diff_ddrive" xmlns:xacro="https://www.ros.org/wiki/xacro" >

<xacro:property name="props" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')}"/>
<xacro:property name="Wheel_width" value="${props['wheel_width']}" />
<xacro:property name="wheel_radius" value="${props['wheel_radius']}" />
<xacro:property name="wheel_base" value="${props['wheel_base']}" />
<xacro:property name="chassis_length" value="${props['chassis_length']}" />
<xacro:property name="chassis_thinkness" value="${props['chassis_thinkness']}" />
<xacro:property name="wheel_axel_offset" value="${props['wheel_axel_offset']}" />


  <link name="base_link" >
    <pose>0 0 ${chassis_thinkness/2 + wheel_radius-wheel_axel_offset} 0 0 0</pose>

    <inertial>
      <mass value="0.94"/>
      <origin rpy="0 0 0" xyz="0 0 ${chassis_thinkness/2 + wheel_radius-wheel_axel_offset}"/>
      <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
    </inertial>

    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${chassis_thinkness/2 + wheel_radius-wheel_axel_offset}"/>
      <geometry>
          <box size="${chassis_length} ${wheel_base+Wheel_width} ${chassis_thinkness}"/>
       </geometry>
       <material name="green_mat">
           <color rgba="0 1 0 1" />
       </material>
     </visual>

  </link>

  <link name="link_right_wheel">
    <visual name="link_right_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${Wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="red_mat">
          <color rgba="1 0 0 0.5" />
      </material>
    </visual>
  </link>

  <joint name="odometer/right_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="${wheel_radius} ${(wheel_base+Wheel_width)/2} ${wheel_radius}"/>
    <child link="link_right_wheel"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="link_left_wheel">
    <visual name="link_left_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${Wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="red_mat">
          <color rgba="1 0 0 0.5" />
      </material>
    </visual>
  </link>

  <joint name="odometer/left_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="${wheel_radius} ${-(wheel_base+Wheel_width)/2} ${wheel_radius}"/>
    <child link="link_left_wheel"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="link_caster">
    <visual name="caster_visual">
      <origin rpy="0 0 0" xyz="${-chassis_length/2 + (wheel_radius/2-wheel_axel_offset/2)} 0 ${wheel_radius/2-wheel_axel_offset/2}"/>
      <geometry>
        <sphere radius="${wheel_radius/2-wheel_axel_offset/2}"/>
      </geometry>
      <material name="red_mat">
        <color rgba="1 0 0 0.5"/>
      </material>
    </visual>
  </link>

  <joint name="joint_caster" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <child link="link_caster"/>
    <parent link="base_link"/>
  </joint>




</robot>
