<?xml version="1.0" ?>

<robot name="diff_ddrive" xmlns:xacro="https://www.ros.org/wiki/xacro" >

<xacro:property name="props" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')}"/>
<xacro:property name="Wheel_width" value="${props['wheel_width']}" />
<xacro:property name="wheel_radius" value="${props['wheel_radius']}" />
<xacro:property name="wheel_base" value="${props['wheel_base']}" />
<xacro:property name="chassis_length" value="${props['chassis_length']}" />
<xacro:property name="chassis_thinkness" value="${props['chassis_thinkness']}" />




  <link name="base_link" >
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_radius}"/>
      <geometry>
          <box size="${chassis_length} ${wheel_base+Wheel_width} ${chassis_thinkness}"/>
       </geometry>
       <material name="green_mat">
           <color rgba="0 1 0 1" />
       </material>
     </visual>
  </link>

  <link name="link_right_wheel">
    <visual name="link_right_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${Wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="red_mat">
          <color rgba="1 0 0 0.5" />
      </material>
    </visual>
  </link>

  <joint name="right_wheel_axle" type="continuous">
    <origin rpy="0 0 0" xyz="0 ${(wheel_base+Wheel_width)/2} ${wheel_radius}"/>
    <child link="link_right_wheel"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="link_left_wheel">
    <visual name="link_left_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${Wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="red_mat">
          <color rgba="1 0 0 0.5" />
      </material>
    </visual>
  </link>

  <joint name="left_wheel_axle" type="continuous">
    <origin rpy="0 0 0" xyz="0 ${-(wheel_base+Wheel_width)/2} ${wheel_radius}"/>
    <child link="link_left_wheel"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="link_caster">
    <visual name="caster_visual">
      <origin rpy="0 0 0" xyz="${chassis_length/2-wheel_radius/2+chassis_thinkness/4} 0 ${wheel_radius/2-chassis_thinkness/4}"/>
      <geometry>
        <sphere radius="${wheel_radius/2-chassis_thinkness/4}"/>
      </geometry>
      <material name="blue_mat">
        <color rgba="0.203125 0.23828125 0.28515625 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="joint_caster" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <child link="link_caster"/>
    <parent link="base_link"/>
  </joint>




</robot>
